version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - APP_NAME=${PROJETO}
        - AWS_ID=${ECOBE_AWS_ACCESS_KEY_ID}
        - AWS_KEY=${ECOBE_AWS_SECRET_ACCESS_KEY}
    image: ${DOCKER_IMAGE_NAME}
    container_name: api
    volumes:
      - .:/home/${PROJETO}/api
    ports:
      - "8000:8000"
    environment:
      ECOBE_ENV: ${ECOBE_ENV}
      ECOBE_AWS_PROFILE: ${AWS_PROFILE}
      ECOBE_AWS_DEFAULT_PROFILE: ${AWS_DEFAULT_PROFILE}
      ECOBE_AWS_ACCESS_KEY_ID: ${ECOBE_AWS_ACCESS_KEY_ID}
      ECOBE_AWS_SECRET_ACCESS_KEY: ${ECOBE_AWS_SECRET_ACCESS_KEY}
      ECOBE_AWS_REGION: "us-east-1"

    stdin_open: true
    tty: true

    # depends_on:
    #   - localstack

  # localstack:
  #   image: localstack/localstack:latest
  #   container_name: localstack
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #   volumes:
  #     - $PWD/.docker/localstack:/var/lib/localstack
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   environment:
  #     - AWS_ENDPOINT_URL="http://127.0.0.1:4566"
  #     - AWS_ENDPOINT_URL_DYNAMODB="http://127.0.0.1:4566"
  #     - AWS_ACCESS_KEY_ID=localstack
  #     - AWS_SECRET_ACCESS_KEY=localstack
  #     - AWS_DEFAULT_REGION=us-east-1
  #     - PERSISTENCE=1
  #     - SERVICES=dynamodb,s3
  #     # - DEBUG=1

  # dynamodb:
  #   image: "aaronshaf/dynamodb-admin"
  #   container_name: dynamodb-admin
  #   depends_on:
  #     - localstack
  #   restart: always
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - DYNAMO_ENDPOINT=http://127.0.0.1:4566
  #     - AWS_ACCESS_KEY_ID=localstack
  #     - AWS_SECRET_ACCESS_KEY=localstack
  #     - AWS_REGION="us-east-1"
